### ISSUE TITLE
Fix Asterisk and Score Display

### ISSUE THREAD

**Issue by samuelsinyangwe** [campaignzero/police-scorecard#26]
Overview:
---

Where it currently says at the bottom of the rankings section that “ * An asterisk indicates this location did not publish enough data to evaluate. Click below to add data to the Scorecard.” it does not currently identify departments with an asterisk.

---

> Info about the Environment:

* **URL**: https://dev.policescorecard.org/or

Acceptance Criteria:
---

> Issue will be considered complete when the following criteria are met:

- [x] Let’s make it so the score still displays but there’s an asterisk next to the score in the rankings in the table like “37%*” and it would still show the color for the score. And let’s set it so it displays the asterisk for all departments where the column completeness<50%.

Documentation:
---

> Screenshots, Attachments, Linked GitHub Issues, etc

![C226A27F-23BB-4EDD-A37E-2EFFF44ACD50](https://user-images.githubusercontent.com/61093397/93039888-b08d8700-f616-11ea-9f13-ba1c0cedfa4d.png)

Dev & QA Notes:
---

> Any additional notes from developers or QA required to complete this issue.

**Comment by manifestinteractive** [comment]
This is fixed on Development
